#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

if ! command -v gpg >/dev/null 2>&1; then
  echo "gpg is required but not found in PATH" >&2
  exit 1
fi

CLIENT_NAME="${1:-local-smoketest}"
KEY_NAME="${2:-ZT Smoke Test}"
KEY_EMAIL="${3:-zt-smoketest@local}"
GNUPGHOME_DIR="${REPO_ROOT}/tmp/gnupg-smoketest"
RECIP_FILE="${REPO_ROOT}/tools/secure-pack/recipients/${CLIENT_NAME}.txt"

mkdir -p "${GNUPGHOME_DIR}"
chmod 700 "${GNUPGHOME_DIR}"

export GNUPGHOME="${GNUPGHOME_DIR}"

if ! gpg --batch --list-secret-keys "${KEY_EMAIL}" >/dev/null 2>&1; then
  echo "[setup] generating local test key in ${GNUPGHOME_DIR}"
  cat >"${REPO_ROOT}/tmp/gpg-keygen-batch.txt" <<EOF
%no-protection
Key-Type: RSA
Key-Length: 3072
Subkey-Type: RSA
Subkey-Length: 3072
Name-Real: ${KEY_NAME}
Name-Email: ${KEY_EMAIL}
Expire-Date: 0
%commit
EOF
  gpg --batch --generate-key "${REPO_ROOT}/tmp/gpg-keygen-batch.txt"
else
  echo "[setup] existing local test key found for ${KEY_EMAIL}"
fi

FPR="$(gpg --batch --with-colons --list-secret-keys "${KEY_EMAIL}" | awk -F: '/^fpr:/ {print $10; exit}')"
if [[ -z "${FPR}" ]]; then
  echo "failed to resolve fingerprint for ${KEY_EMAIL}" >&2
  exit 1
fi

mkdir -p "$(dirname "${RECIP_FILE}")"
cat >"${RECIP_FILE}" <<EOF
# Local smoke test recipient fingerprint (generated by setup-secure-pack-localtest-gpg.sh)
${FPR}
EOF

echo "[setup] wrote recipient file: ${RECIP_FILE}"
echo "[setup] fingerprint: ${FPR}"
echo
echo "Next steps:"
echo "  export GNUPGHOME='${GNUPGHOME_DIR}'"
echo "  cd '${REPO_ROOT}'"
echo "  go run ./gateway/zt send --client '${CLIENT_NAME}' safe.txt"
echo "  go run ./gateway/zt verify ./bundle_${CLIENT_NAME}_*.spkg.tgz"
echo
echo "Optional strict scanner mode (will deny if no scanners are installed):"
echo "  export ZT_SCAN_STRICT=1"
